# Generated by Django 3.1 on 2020-08-23 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=16, verbose_name='Subject')),
                ('body', models.CharField(max_length=200, verbose_name='Body')),
                ('email', models.CharField(max_length=32, verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
